In [32]:
import pandas as pd
import numpy as np

#### Zu den Daten
Die Auswertung der Flugpassagiere nach Destination ist beim BfS auf Anfrage erhältlich. Aktuell ist der Zeitraum 2018 bis 2020 verfügbar.

Im Excel (wmove_wvs_2018_2020__kunde.xlsx) enthalten sind fünf Tabellenblätter:
* flughäfen: Übersicht über die verwendeten Abkürzungen
* wmove: Etappenziel nach Land
* wmove1: Etappenziel nach Land und Flughafen
* wvs: Endziel nach Land
* wvs1: Endziel nach Land und Flughafen

*Art der Passagiere*
* Passagiere: Passagiere, die eine Reise an diesem Flughafen antreten oder an diesem Flughafen umsteigen.
* Transitpassagiere: Passagiere, die nach einer Zwischenlandung im gleichen Flugzeug weiterfliegen.

### 1. Schritt: Daten einlesen

In [2]:
#Zwei relevante Tabellenblätter einlesen
xls = pd.ExcelFile('wmove_wvs_2018_2020__kunde.xlsx')
etappe = pd.read_excel(xls, 'wmove1', skiprows=3) #Etappenziel: Erster Flughafen nach Abflug aus ZRH
end = pd.read_excel(xls, 'wvs1', skiprows=4) #Endziel: Zielflughafen nach allfälligem Umsteigen

In beiden Dataframes sind Abflüge von allen Schweizer Flughäfen enthalten. Uns interessieren jene ab Zürich. Wir filtern nach diesen und bereinigen die Daten.

In [3]:
#Filtern nach Abflügen aus Zürich (=LSZH bzw. ZRH) und die Spalte dann entfernen
etappe = etappe[etappe['Flughafen'] == 'LSZH']
etappe.drop('Flughafen',axis=1,inplace=True)
end = end[end['Fluhafen'] == 'ZRH'] #Flughafen ist im Originaldokument falsch geschrieben
end.drop('Fluhafen',axis=1,inplace=True)

In [4]:
#Jahr und Monat sind in unterschiedlichen Spalten erfasst, die wir zusammenführen
etappe['Datum'] = etappe['Jahr'].astype(str) + '-' + etappe['Monat'].astype(str)
end['Datum'] = end['Jahr'].astype(str) + '-' + end['Monat'].astype(str)

In [5]:
#Die Spalten Monat und Jahr brauchen wir nun nicht mehr separat
etappe.drop(['Monat','Jahr'], axis=1, inplace=True)
end.drop(['Monat','Jahr'], axis=1, inplace=True)

In [6]:
#Die Datumsspalte ist noch nicht als solche formatiert. Das ändern wir
etappe['Datum'] =  pd.to_datetime(etappe['Datum'], format='%Y-%m')
end['Datum'] =  pd.to_datetime(end['Datum'], format='%Y-%m')

In [7]:
#Im Dataframe etappe sind Passagiere und Transitpassagiere getrennt, im Dataframe end nicht. Wir rechnen sie im Dataframe etappe zusammen.
etappe['Passagiere'] = etappe['Passagiere'] + etappe['Transitpassagiere']
etappe.drop('Transitpassagiere', axis=1, inplace=True)

In [8]:
#Wir pivotieren das Dataframe und trennen dabei im Datafram etappe gleich Flüge und Passagiere (im Dataframe end sind die Flüge nicht erfasst.)
etappe_pax = etappe.pivot(index='Datum', columns=['Zielkontinent','Zielland','Ort/Flughafen'], values='Passagiere')
etappe_flights = etappe.pivot(index='Datum', columns=['Zielkontinent','Zielland','Ort/Flughafen'], values='Flüge')
end_pax = end.pivot(index='Datum', columns=['Kontinent','Zielland','Ort/Flughafen'], values='Passagiere')

(6.1.22) Noch nicht ganz klar, ob Etappenziele oder Endziele sinnvoller ist. So oder so ist die Zahl deutlich kleiner als jene über Stat-Tab, weil dort An- und Abflüge drin sind, hier aber nur Abflüge. Aktuell arbeiten wir mit dem File Etappenziele, weil - Vermutung - dort mehr Flüge drin sein dürfen (alle Abflüge ab Zürich) als im anderen (nur Abflüge direkt ans Ziel).

* Fragen beim BfS deponiert: Gibts aktuellere Daten? Habe ich die Daten richtig verstanden?
* Frage beim BfS noch nicht deponiert: Gibt es genauere Daten? In der quartalsweisen Auswertung auf der Webseite des BAG sind sogar Flughäfen erfasst, nicht nur Zielorte (also LHR, LGW und Co. statt nur London)? Gibt es auch Daten zu den Ankünften?

In [17]:
#Zum Vergleich der Bedeutung eines Zielflughafens sind relative Angaben sinnvoller.
etappe_pax_rel = etappe_pax.div(etappe_pax.sum(axis=1), axis=0) * 100

In [25]:
#Ein erster Blick in die sortieren Zahlen zur Darstellung der bedeutendsten Flughäfen im Januar 2018...
etappe_pax_rel.sort_values(by='2018-01-01',axis=1,ascending=False)

Zielkontinent              1                                                  \
Zielland      Grossbritanien Niederlande Deutschland Oesterreich Deutschland
Ort/Flughafen         London   Amsterdam      Berlin        Wien  Düsseldorf
Datum
2018-01-01          7.884854    3.712482    3.591083    3.085761    2.930681
2018-02-01          7.615960    3.618086    4.014039    3.281821    2.673954
2018-03-01          6.593504    3.554306    4.045680    3.422023    2.583426
2018-04-01          6.523748    3.352914    4.375361    3.454252    2.330988
2018-05-01          5.654953    3.346158    4.216133    3.455868    2.370059
2018-06-01          5.955305    3.147783    4.087141    3.265157    2.268168
2018-07-01          5.568919    2.616494    3.573306    2.855331    1.843393
2018-08-01          5.729266    3.003135    3.778679    2.654619    1.929922
2018-09-01          5.834615    2.972444    4.191683    3.070230    2.070904
2018-10-01          5.834334    3.153610    4.377076    2.998503    2.292249
2018-11-01          6.610780    3.565831    4.901502    3.755319    3.298123
2018-12-01          6.418055    3.267617    4.488744    3.487827    2.764389
2019-01-01          7.381066    3.415439    4.234561    2.899152    2.967051
2019-02-01          7.182531    3.411638    4.385273    3.042078    2.771398
2019-03-01          6.833901    3.340362    4.455713    3.150187    2.965369
2019-04-01          6.304579    3.212223    3.763540    3.236916    2.351844
2019-05-01          5.719324    3.313894    3.789935    3.354209    2.356257
2019-06-01          5.815693    3.076529    3.452150    2.917428    2.284486
2019-07-01          5.448108    2.631857    3.074789    2.647633    1.935067
2019-08-01          5.723614    2.943124    3.008393    2.432566    1.995234
2019-09-01          5.945419    2.866033    3.324946    2.873476    2.225906
2019-10-01          5.989355    3.060978    3.569527    2.919836    2.459401
2019-11-01          6.621269    3.475425    4.142524    3.453350    2.727049
2019-12-01          6.891915    3.437957    4.159964    3.404361    2.225255
2020-01-01          7.591292    3.499930    3.957794    2.713765    2.525773
2020-02-01          7.409423    3.501725    4.082273    2.886303    2.438841
2020-03-01          7.815209    4.056538    4.495525    2.727672    2.150540
2020-04-01         10.558793   11.507256    5.633642         NaN    2.673980
2020-05-01          9.571550   10.261988    5.457297         NaN    2.738106
2020-06-01          2.858036    4.447788    5.853844    5.028190    3.440392
2020-07-01          2.700267    2.766653    5.050519    4.114898    1.660208
2020-08-01          6.088122    4.404270    5.888327    4.016202    2.381465
2020-09-01          3.217974    4.758051    6.874225    3.676485    3.168343
2020-10-01          2.171470    2.630757    5.401864    2.145358    2.745928
2020-11-01          3.711506    5.414239    2.996255    3.506034    1.504196
2020-12-01          3.773082    4.675716    3.109304    3.410356    1.396025

Zielkontinent                                              \
Zielland                 Frankreich   Schweiz Deutschland
Ort/Flughafen  Frankfurt      Paris    Genève     Hamburg
Datum
2018-01-01      2.769620   2.698165  2.665953    2.504368
2018-02-01      2.580069   2.478827  2.413750    2.437584
2018-03-01      2.402595   2.660937  2.294793    2.602181
2018-04-01      2.132253   2.360356  2.059094    2.473589
2018-05-01      2.030018   2.593751  1.885976    2.594362
2018-06-01      2.084357   2.570736  1.703855    2.410356
2018-07-01      2.087347   2.068464  1.708228    2.314490
2018-08-01      1.878531   2.074848  2.142144    2.243293
2018-09-01      2.056734   2.418416  1.719323    2.301550
2018-10-01      2.056053   2.337353  1.632725    2.439438
2018-11-01      2.443994   2.722532  2.047523    2.617745
2018-12-01      2.264484   2.477110  2.113132    2.562586
2019-01-01      2.407304   2.521619  2.629429    2.389566
2019-02-01      2.354083   2.457322  2.199027    2.262932
2019-03-01      2.280925   2.666631  2.246522    2.672490
2019-04-01      2.137163   2.140258  1.919602    2.267901
2019-05-01      2.017000   2.388238  1.740354    2.324275
2019-06-01      2.013519   2.257969  1.885106    2.148578
2019-07-01      2.054738   1.814856  1.726978    2.033743
2019-08-01      1.861392   1.749800  2.229476    1.901848
2019-09-01      1.980971   2.176655  1.830922    2.001702
2019-10-01      2.044163   2.164165  1.700883    2.079893
2019-11-01      2.354685   2.626615  2.059129    2.280066
2019-12-01      2.262202   2.656047  2.228522    2.166442
2020-01-01      2.324102   2.756366  2.649863    2.039085
2020-02-01      2.230092   2.606201  2.267473    2.103721
2020-03-01      3.089526   2.490569  2.541908    2.595232
2020-04-01     18.866415   1.097017       NaN    2.616844
2020-05-01     19.540339        NaN       NaN    0.510735
2020-06-01      6.277909   0.911640       NaN    3.860547
2020-07-01      2.502726   0.832803  0.997960    3.302605
2020-08-01      2.292937   1.104478  1.722052    4.233884
2020-09-01      2.796495   0.844103  1.792811    4.600378
2020-10-01      3.087246   0.294223  1.670684    3.540471
2020-11-01      3.980268   0.552261  1.938549    1.513733
2020-12-01      3.598514   1.150374  2.119909    1.624427

Zielkontinent                              5  ...          4         1  \
Zielland      Vereinigte Staaten von Amerika  ... Australien Moldawien
Ort/Flughafen                       New York  ...     Sydney  Kishinev
Datum                                         ...
2018-01-01                          2.416859  ...        NaN       NaN
2018-02-01                          2.021631  ...        NaN       NaN
2018-03-01                          2.389233  ...        NaN       NaN
2018-04-01                          2.294483  ...        NaN       NaN
2018-05-01                          2.221363  ...        NaN       NaN
2018-06-01                          2.158070  ...        NaN       NaN
2018-07-01                          2.156361  ...        NaN       NaN
2018-08-01                          2.384617  ...        NaN       NaN
2018-09-01                          2.270966  ...        NaN       NaN
2018-10-01                          2.415402  ...        NaN       NaN
2018-11-01                          2.460286  ...        NaN       NaN
2018-12-01                          2.501824  ...        NaN       NaN
2019-01-01                          2.508216  ...        NaN       NaN
2019-02-01                          2.006916  ...        NaN       NaN
2019-03-01                          2.329222  ...        NaN       NaN
2019-04-01                          2.306704  ...        NaN       NaN
2019-05-01                          2.222401  ...        NaN       NaN
2019-06-01                          2.082958  ...        NaN       NaN
2019-07-01                          2.107885  ...        NaN       NaN
2019-08-01                          2.326436  ...        NaN       NaN
2019-09-01                          2.262914  ...        NaN       NaN
2019-10-01                          2.429508  ...        NaN       NaN
2019-11-01                          2.288459  ...        NaN       NaN
2019-12-01                          2.528368  ...        NaN       NaN
2020-01-01                          2.576679  ...        NaN       NaN
2020-02-01                          2.222376  ...        NaN       NaN
2020-03-01                          2.232633  ...        NaN       NaN
2020-04-01                          2.605417  ...   0.171409       NaN
2020-05-01                          2.326681  ...        NaN  0.463445
2020-06-01                          1.068954  ...        NaN       NaN
2020-07-01                          0.474152  ...        NaN       NaN
2020-08-01                          0.840107  ...        NaN       NaN
2020-09-01                          1.028881  ...        NaN       NaN
2020-10-01                          0.789414  ...        NaN       NaN
2020-11-01                          1.248439  ...        NaN       NaN
2020-12-01                          0.933993  ...        NaN       NaN

Zielkontinent                   2                   1                       \
Zielland       Kroatien  Algerien     Kenia   Italien   Slovakei  Dänemark
Ort/Flughafen      Brac     Alger   Nairobi   Ravenna Bratislava    Aarhus
Datum
2018-01-01          NaN       NaN       NaN       NaN        NaN       NaN
2018-02-01          NaN       NaN       NaN       NaN        NaN       NaN
2018-03-01          NaN       NaN       NaN       NaN        NaN       NaN
2018-04-01          NaN       NaN       NaN       NaN        NaN       NaN
2018-05-01          NaN       NaN       NaN       NaN        NaN       NaN
2018-06-01          NaN       NaN       NaN       NaN        NaN       NaN
2018-07-01          NaN       NaN       NaN       NaN        NaN       NaN
2018-08-01          NaN       NaN       NaN       NaN        NaN       NaN
2018-09-01          NaN       NaN       NaN       NaN        NaN       NaN
2018-10-01          NaN       NaN       NaN       NaN        NaN       NaN
2018-11-01          NaN       NaN       NaN       NaN        NaN       NaN
2018-12-01          NaN       NaN       NaN       NaN        NaN       NaN
2019-01-01          NaN       NaN       NaN       NaN        NaN       NaN
2019-02-01          NaN       NaN       NaN       NaN        NaN       NaN
2019-03-01          NaN       NaN       NaN       NaN        NaN       NaN
2019-04-01          NaN       NaN       NaN       NaN        NaN       NaN
2019-05-01          NaN       NaN       NaN       NaN        NaN       NaN
2019-06-01          NaN       NaN       NaN       NaN        NaN       NaN
2019-07-01          NaN       NaN       NaN       NaN        NaN       NaN
2019-08-01          NaN       NaN       NaN       NaN        NaN       NaN
2019-09-01          NaN       NaN       NaN       NaN        NaN       NaN
2019-10-01          NaN       NaN       NaN       NaN        NaN       NaN
2019-11-01          NaN       NaN       NaN       NaN        NaN       NaN
2019-12-01          NaN       NaN       NaN       NaN        NaN       NaN
2020-01-01          NaN       NaN       NaN       NaN        NaN       NaN
2020-02-01          NaN       NaN       NaN       NaN        NaN       NaN
2020-03-01          NaN       NaN       NaN       NaN        NaN       NaN
2020-04-01          NaN       NaN       NaN       NaN        NaN       NaN
2020-05-01          NaN       NaN       NaN       NaN        NaN       NaN
2020-06-01          NaN       NaN       NaN       NaN        NaN       NaN
2020-07-01     0.009175  0.000270       NaN       NaN        NaN       NaN
2020-08-01          NaN  0.001819  0.027589       NaN        NaN       NaN
2020-09-01          NaN       NaN  0.054975  0.000764   0.013744       NaN
2020-10-01          NaN  0.002331  0.148744       NaN        NaN       NaN
2020-11-01          NaN  0.000867       NaN       NaN        NaN  0.023408
2020-12-01          NaN       NaN       NaN       NaN        NaN       NaN

Zielkontinent         3         5
Zielland        Bahrein    Kanada
Ort/Flughafen   Bahrain  Edmonton
Datum
2018-01-01          NaN       NaN
2018-02-01          NaN       NaN
2018-03-01          NaN       NaN
2018-04-01          NaN       NaN
2018-05-01          NaN       NaN
2018-06-01          NaN       NaN
2018-07-01          NaN       NaN
2018-08-01          NaN       NaN
2018-09-01          NaN       NaN
2018-10-01          NaN       NaN
2018-11-01          NaN       NaN
2018-12-01          NaN       NaN
2019-01-01          NaN       NaN
2019-02-01          NaN       NaN
2019-03-01          NaN       NaN
2019-04-01          NaN       NaN
2019-05-01          NaN       NaN
2019-06-01          NaN       NaN
2019-07-01          NaN       NaN
2019-08-01          NaN       NaN
2019-09-01          NaN       NaN
2019-10-01          NaN       NaN
2019-11-01          NaN       NaN
2019-12-01          NaN       NaN
2020-01-01          NaN       NaN
2020-02-01          NaN       NaN
2020-03-01          NaN       NaN
2020-04-01          NaN       NaN
2020-05-01          NaN       NaN
2020-06-01          NaN       NaN
2020-07-01          NaN       NaN
2020-08-01          NaN       NaN
2020-09-01          NaN       NaN
2020-10-01          NaN       NaN
2020-11-01     0.039014       NaN
2020-12-01          NaN  0.047562

[36 rows x 281 columns]

In [24]:
#...und im Juli 2020.
etappe_pax_rel.sort_values(by='2020-07-01',axis=1,ascending=False)

Zielkontinent           1                                           \
Zielland      Deutschland Oesterreich   Portugal           Spanien
Ort/Flughafen      Berlin        Wien      Porto Palma De Mallorca
Datum
2018-01-01       3.591083    3.085761   0.604477          0.467549
2018-02-01       4.014039    3.281821   0.823512          0.830352
2018-03-01       4.045680    3.422023   0.868058          1.141587
2018-04-01       4.375361    3.454252   1.011146          1.582443
2018-05-01       4.216133    3.455868   1.040873          1.957540
2018-06-01       4.087141    3.265157   0.924731          1.813224
2018-07-01       3.573306    2.855331   1.031126          1.775963
2018-08-01       3.778679    2.654619   1.061182          1.699345
2018-09-01       4.191683    3.070230   1.023948          1.883118
2018-10-01       4.377076    2.998503   1.009893          1.489071
2018-11-01       4.901502    3.755319   0.757396          0.455992
2018-12-01       4.488744    3.487827   1.014978          0.551207
2019-01-01       4.234561    2.899152   0.734766          0.375464
2019-02-01       4.385273    3.042078   0.938364          0.783109
2019-03-01       4.455713    3.150187   0.902995          1.015995
2019-04-01       3.763540    3.236916   0.947418          1.795631
2019-05-01       3.789935    3.354209   0.924830          1.830217
2019-06-01       3.452150    2.917428   0.865371          2.001356
2019-07-01       3.074789    2.647633   0.862889          1.987614
2019-08-01       3.008393    2.432566   0.884306          2.196504
2019-09-01       3.324946    2.873476   0.885688          2.304652
2019-10-01       3.569527    2.919836   0.928130          1.680954
2019-11-01       4.142524    3.453350   0.848719          0.511932
2019-12-01       4.159964    3.404361   1.098511          0.561906
2020-01-01       3.957794    2.713765   0.824760          0.468514
2020-02-01       4.082273    2.886303   0.970686          0.812947
2020-03-01       4.495525    2.727672   1.120037          0.974948
2020-04-01       5.633642         NaN   6.056451               NaN
2020-05-01       5.457297         NaN  10.966613               NaN
2020-06-01       5.853844    5.028190   4.585560          1.089474
2020-07-01       5.050519    4.114898   4.048781          3.998856
2020-08-01       5.888327    4.016202   3.612065          1.655959
2020-09-01       6.874225    3.676485   2.739611          0.356577
2020-10-01       5.401864    2.145358   0.856558          0.408462
2020-11-01       2.996255    3.506034   1.088917          1.935081
2020-12-01       3.109304    3.410356   4.118038          1.654741

Zielkontinent                                                                \
Zielland      Griechenland Deutschland  Portugal Niederlande Grossbritanien
Ort/Flughafen        Athen     Hamburg    Lisboa   Amsterdam         London
Datum
2018-01-01        1.362146    2.504368  1.547864    3.712482       7.884854
2018-02-01        1.403815    2.437584  1.915725    3.618086       7.615960
2018-03-01        1.740514    2.602181  1.882009    3.554306       6.593504
2018-04-01        1.660138    2.473589  1.906158    3.352914       6.523748
2018-05-01        1.752081    2.594362  2.007359    3.346158       5.654953
2018-06-01        1.665069    2.410356  1.827269    3.147783       5.955305
2018-07-01        1.569409    2.314490  1.744410    2.616494       5.568919
2018-08-01        1.472032    2.243293  1.615258    3.003135       5.729266
2018-09-01        1.537781    2.301550  1.727530    2.972444       5.834615
2018-10-01        1.405791    2.439438  1.710491    3.153610       5.834334
2018-11-01        1.356406    2.617745  1.541821    3.565831       6.610780
2018-12-01        1.676206    2.562586  1.714385    3.267617       6.418055
2019-01-01        1.266919    2.389566  1.313335    3.415439       7.381066
2019-02-01        1.352508    2.262932  1.610209    3.411638       7.182531
2019-03-01        1.696087    2.672490  1.683615    3.340362       6.833901
2019-04-01        1.563024    2.267901  1.647831    3.212223       6.304579
2019-05-01        1.621588    2.324275  1.641407    3.313894       5.719324
2019-06-01        1.574752    2.148578  1.638463    3.076529       5.815693
2019-07-01        1.687807    2.033743  1.530706    2.631857       5.448108
2019-08-01        1.628498    1.901848  1.405517    2.943124       5.723614
2019-09-01        1.549049    2.001702  1.451103    2.866033       5.945419
2019-10-01        1.465221    2.079893  1.466715    3.060978       5.989355
2019-11-01        1.479877    2.280066  1.619992    3.475425       6.621269
2019-12-01        1.726100    2.166442  1.769078    3.437957       6.891915
2020-01-01        1.353463    2.039085  1.387368    3.499930       7.591292
2020-02-01        1.431777    2.103721  1.660969    3.501725       7.409423
2020-03-01        1.712545    2.595232  2.102673    4.056538       7.815209
2020-04-01        5.096560    2.616844  3.073934   11.507256      10.558793
2020-05-01        5.665374    0.510735  5.750497   10.261988       9.571550
2020-06-01        4.734080    3.860547  3.276238    4.447788       2.858036
2020-07-01        3.439426    3.302605  2.889442    2.766653       2.700267
2020-08-01        3.151234    4.233884  3.114550    4.404270       6.088122
2020-09-01        3.493997    4.600378  3.374120    4.758051       3.217974
2020-10-01        4.682859    3.540471  1.370866    2.630757       2.171470
2020-11-01        1.852719    1.513733  3.035268    5.414239       3.711506
2020-12-01        1.725823    1.624427  3.383700    4.675716       3.773082

Zielkontinent            ...         7                    4         1  \
Zielland         Türkei  ... Kolumbien      Peru Australien Moldawien
Ort/Flughafen  Istanbul  ...    Bogota      Lima     Sydney  Kishinev
Datum                    ...
2018-01-01     1.408313  ...       NaN       NaN        NaN       NaN
2018-02-01     1.489099  ...       NaN       NaN        NaN       NaN
2018-03-01     1.497192  ...       NaN       NaN        NaN       NaN
2018-04-01     1.524823  ...       NaN       NaN        NaN       NaN
2018-05-01     1.305535  ...       NaN       NaN        NaN       NaN
2018-06-01     1.178399  ...       NaN       NaN        NaN       NaN
2018-07-01     1.360114  ...       NaN       NaN        NaN       NaN
2018-08-01     1.387741  ...       NaN       NaN        NaN       NaN
2018-09-01     1.239512  ...       NaN       NaN        NaN       NaN
2018-10-01     1.343225  ...       NaN       NaN        NaN       NaN
2018-11-01     1.182470  ...       NaN       NaN        NaN       NaN
2018-12-01     1.275583  ...       NaN       NaN        NaN       NaN
2019-01-01     1.128658  ...       NaN       NaN        NaN       NaN
2019-02-01     1.335269  ...       NaN       NaN        NaN       NaN
2019-03-01     1.303852  ...       NaN       NaN        NaN       NaN
2019-04-01     1.166923  ...       NaN       NaN        NaN       NaN
2019-05-01     1.199149  ...       NaN       NaN        NaN       NaN
2019-06-01     1.189655  ...       NaN       NaN        NaN       NaN
2019-07-01     1.314579  ...       NaN       NaN        NaN       NaN
2019-08-01     1.330741  ...       NaN       NaN        NaN       NaN
2019-09-01     1.333818  ...       NaN       NaN        NaN       NaN
2019-10-01     1.465505  ...       NaN       NaN        NaN       NaN
2019-11-01     1.252007  ...       NaN       NaN        NaN       NaN
2019-12-01     1.294302  ...       NaN       NaN        NaN       NaN
2020-01-01     1.104012  ...       NaN       NaN        NaN       NaN
2020-02-01     1.377861  ...       NaN       NaN        NaN       NaN
2020-03-01     1.590026  ...  0.007936  0.008433        NaN       NaN
2020-04-01          NaN  ...       NaN       NaN   0.171409       NaN
2020-05-01          NaN  ...       NaN       NaN        NaN  0.463445
2020-06-01     2.070488  ...       NaN       NaN        NaN       NaN
2020-07-01     2.519727  ...       NaN       NaN        NaN       NaN
2020-08-01     2.095265  ...       NaN       NaN        NaN       NaN
2020-09-01     2.533071  ...       NaN       NaN        NaN       NaN
2020-10-01     3.360486  ...       NaN       NaN        NaN       NaN
2020-11-01     3.835483  ...       NaN       NaN        NaN       NaN
2020-12-01     3.094147  ...       NaN       NaN        NaN       NaN

Zielkontinent         2         1                              3         5
Zielland          Kenia   Italien   Slovakei  Dänemark   Bahrein    Kanada
Ort/Flughafen   Nairobi   Ravenna Bratislava    Aarhus   Bahrain  Edmonton
Datum
2018-01-01          NaN       NaN        NaN       NaN       NaN       NaN
2018-02-01          NaN       NaN        NaN       NaN       NaN       NaN
2018-03-01          NaN       NaN        NaN       NaN       NaN       NaN
2018-04-01          NaN       NaN        NaN       NaN       NaN       NaN
2018-05-01          NaN       NaN        NaN       NaN       NaN       NaN
2018-06-01          NaN       NaN        NaN       NaN       NaN       NaN
2018-07-01          NaN       NaN        NaN       NaN       NaN       NaN
2018-08-01          NaN       NaN        NaN       NaN       NaN       NaN
2018-09-01          NaN       NaN        NaN       NaN       NaN       NaN
2018-10-01          NaN       NaN        NaN       NaN       NaN       NaN
2018-11-01          NaN       NaN        NaN       NaN       NaN       NaN
2018-12-01          NaN       NaN        NaN       NaN       NaN       NaN
2019-01-01          NaN       NaN        NaN       NaN       NaN       NaN
2019-02-01          NaN       NaN        NaN       NaN       NaN       NaN
2019-03-01          NaN       NaN        NaN       NaN       NaN       NaN
2019-04-01          NaN       NaN        NaN       NaN       NaN       NaN
2019-05-01          NaN       NaN        NaN       NaN       NaN       NaN
2019-06-01          NaN       NaN        NaN       NaN       NaN       NaN
2019-07-01          NaN       NaN        NaN       NaN       NaN       NaN
2019-08-01          NaN       NaN        NaN       NaN       NaN       NaN
2019-09-01          NaN       NaN        NaN       NaN       NaN       NaN
2019-10-01          NaN       NaN        NaN       NaN       NaN       NaN
2019-11-01          NaN       NaN        NaN       NaN       NaN       NaN
2019-12-01          NaN       NaN        NaN       NaN       NaN       NaN
2020-01-01          NaN       NaN        NaN       NaN       NaN       NaN
2020-02-01          NaN       NaN        NaN       NaN       NaN       NaN
2020-03-01          NaN       NaN        NaN       NaN       NaN       NaN
2020-04-01          NaN       NaN        NaN       NaN       NaN       NaN
2020-05-01          NaN       NaN        NaN       NaN       NaN       NaN
2020-06-01          NaN       NaN        NaN       NaN       NaN       NaN
2020-07-01          NaN       NaN        NaN       NaN       NaN       NaN
2020-08-01     0.027589       NaN        NaN       NaN       NaN       NaN
2020-09-01     0.054975  0.000764   0.013744       NaN       NaN       NaN
2020-10-01     0.148744       NaN        NaN       NaN       NaN       NaN
2020-11-01          NaN       NaN        NaN  0.023408  0.039014       NaN
2020-12-01          NaN       NaN        NaN       NaN       NaN  0.047562

[36 rows x 281 columns]

In [35]:
#Die drei bedeutendsten Zielflughäfen pro Monat in ein Dataframe dftop schreiben.
dftop = pd.DataFrame(etappe_pax_rel.columns.values[np.argsort(-etappe_pax_rel.values, axis=1)[:, :3]], 
                  index=etappe_pax_rel.index,
                  columns = ['1st Max','2nd Max','3rd Max']).reset_index()
dftop

,Datum,1st Max,2nd Max,3rd Max
0,2018-01-01,"(1, Grossbritanien, London)","(1, Niederlande, Amsterdam)","(1, Deutschland, Berlin)"
1,2018-02-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
2,2018-03-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
3,2018-04-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Oesterreich, Wien)"
4,2018-05-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Oesterreich, Wien)"
5,2018-06-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Oesterreich, Wien)"
6,2018-07-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Oesterreich, Wien)"
7,2018-08-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
8,2018-09-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Oesterreich, Wien)"
9,2018-10-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
10,2018-11-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Oesterreich, Wien)"
11,2018-12-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Oesterreich, Wien)"
12,2019-01-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
13,2019-02-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
14,2019-03-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
15,2019-04-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Oesterreich, Wien)"
16,2019-05-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Oesterreich, Wien)"
17,2019-06-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
18,2019-07-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Oesterreich, Wien)"
19,2019-08-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
20,2019-09-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Oesterreich, Wien)"
21,2019-10-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
22,2019-11-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
23,2019-12-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
24,2020-01-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
25,2020-02-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
26,2020-03-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
27,2020-04-01,"(1, Deutschland, Frankfurt)","(1, Niederlande, Amsterdam)","(1, Grossbritanien, London)"
28,2020-05-01,"(1, Deutschland, Frankfurt)","(1, Portugal, Porto)","(1, Niederlande, Amsterdam)"
29,2020-06-01,"(1, Serbien / Montenegro / Kosovo, Beograd)","(1, Deutschland, Frankfurt)","(1, Deutschland, Berlin)"
30,2020-07-01,"(1, Deutschland, Berlin)","(1, Oesterreich, Wien)","(1, Portugal, Porto)"
31,2020-08-01,"(1, Grossbritanien, London)","(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)"
32,2020-09-01,"(1, Deutschland, Berlin)","(1, Niederlande, Amsterdam)","(1, Deutschland, Hamburg)"
33,2020-10-01,"(1, Serbien / Montenegro / Kosovo, Pristina (K...","(1, Türkei, Antalya)","(1, Serbien / Montenegro / Kosovo, Beograd)"
34,2020-11-01,"(1, Serbien / Montenegro / Kosovo, Pristina (K...","(1, Serbien / Montenegro / Kosovo, Beograd)","(1, Niederlande, Amsterdam)"
35,2020-12-01,"(1, Serbien / Montenegro / Kosovo, Pristina (K...","(1, Niederlande, Amsterdam)","(3, Vereinigte Arabische Emirate, Dubai)"